# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Scree LLC.
email: webmin@scree.it
description: >- # this means to ignore newlines until "baseurl:"
  We offer a wide array of services including development, website design, hosting, 
  business email, training, and troubleshooting. Let us help you keep moving forward.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://scree.it" # the base hostname & protocol for your site, e.g. http://example.com
# github_repo: jekyll # the GitHub repo name for your project
github_username: landbryo

# Optional social link, you can choose from the following options:
# twitter (default), instagram, medium, or dribbble
social_link: twitter
social_username: landonotis
facebook_username: landon.otis

# Set theme color here
# Choose from: black (default), blue, gray, magenta, orange, red, white, and yellow.
theme_color: blue

# Build settings
markdown: kramdown
theme: jekyll-swiss
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collection settings
collections:
  portfolio:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "portfolio"
    values:
      layout: "page"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
